services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./app
          target: /var/www/app
        - action: sync
          path: ./routes
          target: /var/www/routes
        - action: sync
          path: ./config
          target: /var/www/config
        - action: sync
          path: ./resources
          target: /var/www/resources
        - action: sync
          path: ./database/migrations
          target: /var/www/database/migrations
        - action: sync
          path: ./database/seeders
          target: /var/www/database/seeders
        - action: sync
          path: ./database/factories
          target: /var/www/database/factories
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: composer.json
        - action: rebuild
          path: composer.lock
        - action: rebuild
          path: package.json
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./storage:/var/www/storage
      - ./database:/var/www/database
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
      WATCHPACK_POLLING: "true"
    env_file:
      - .env
    depends_on:
      - mailpit
    networks:
      - chat-network

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
